asset_dir = "assets"
exclude_assets = ["*.luau", "*.rbxm"]
write_dir = "assets"

[creator]
type = "user"
id = 7901125900

[codegen]
output_name = "init"
typescript = false
style = "nested"
strip_extension = true
